with git pat

diff --git a/.github/workflows/merge-main-into-feature.yaml b/.github/workflows/merge-main-into-feature.yaml
--- a/.github/workflows/merge-main-into-feature.yaml
+++ b/.github/workflows/merge-main-into-feature.yaml
@@ -77,7 +77,9 @@ jobs:
               echo "Changes detected in tokens directory."
               git add tokens/
               git commit -m "Merged tokens directory from main into $branch_name"
-              git push origin $branch_name || echo "Failed to push $branch_name"
+              
+              # Push changes using PAT for authentication
+              git push https://x-access-token:${{ secrets.GIT_PAT  }}@github.com/svensson1982/core-web.git $branch_name || echo "Failed to push $branch_name"
             else
               echo "No changes in tokens directory for $branch_name."
             fi
