asdf

diff --git a/.github/workflows/merge-main-into-feature.yaml b/.github/workflows/merge-main-into-feature.yaml
--- a/.github/workflows/merge-main-into-feature.yaml
+++ b/.github/workflows/merge-main-into-feature.yaml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
 env:
-    GIT_PAT: ${{ secrets.WB_GIT_PAT }}
+    PAT: ${{ secrets.WB_GIT_PAT }}
 jobs:
   merge-main:
     runs-on: ubuntu-latest
@@ -82,7 +82,7 @@ jobs:
               git commit -m "Merged tokens directory from main into $branch_name"
               
               # Push changes using PAT for authentication
-              git push https://x-access-token:${{ secrets.WB_GIT_PAT  }}@github.com/svensson1982/core-web.git $branch_name || echo "Failed to push $branch_name"
+              git push https://x-access-token:$PAT@github.com/svensson1982/core-web.git $branch_name || echo "Failed to push $branch_name"
             else
               echo "No changes in tokens directory for $branch_name."
             fi
